// Stable guide selectors are the inventory IDs. Complete instructions and sources
// live in docs/workloads.md; this index routes work, never launches it.
export const workloads = [
  { id: "workloads/foundry-tests", ecosystem: "foundry", summary: "Unit, fuzz, and stateful invariant tests for your contracts",
    recipe: "foundry", profile: "runtime", status: "validated", inputs: ["project"],
    evidence: "2026-09-14: synthetic unit assertion, 128 fuzz runs, and 512 successful invariant handler calls passed",
    requires: ["project compiler and dependencies"], related: ["workloads/foundry-symbolic", "workloads/base-contract-fork", "workloads/bsc-contract-fork"] },
  { id: "workloads/foundry-symbolic", ecosystem: "foundry", summary: "Bounded symbolic properties with prebuilt Forge and Z3",
    recipe: "foundry-symbolic", profile: "foundry-symbolic", status: "validated", inputs: ["project", "property and exploration bounds"],
    evidence: "2026-09-14: Forge 1.8.1/Z3 5.1.0; pass with 3 SMT queries, replay-confirmed counterexample, and incomplete results for missing/empty solver and depth limit",
    requires: ["glibc >= 2.39", "project compiler and dependencies"], related: ["workloads/foundry-tests", "workloads/foundry-source-build"] },
  { id: "workloads/foundry-source-build", ecosystem: "foundry", summary: "Build a changed Foundry revision; restore compatible binaries for unchanged revisions",
    recipe: "foundry-source", profile: "foundry-source", status: "validated", inputs: ["repo", "exact ref"],
    requires: [], evidence: "2026-09-14: source build and same-VM compiled-cache restore passed; cross-rental restore pending",
    related: ["workloads/foundry-tests", "workloads/foundry-symbolic"] },
  { id: "workloads/reth-development", ecosystem: "reth", summary: "Private Reth development-chain RPC and execution checks",
    recipe: "reth", profile: "runtime", status: "validated", inputs: ["workload"], requires: ["Linux x86_64", "transaction signer supplied separately"],
    evidence: "2026-09-14: Reth 2.5.2/Cast 1.8.1; signed type-2 deployment, storage update, ETH transfer and included revert passed receipt/state/fee checks; wrong-chain transaction rejected",
    related: ["workloads/reth-source-build", "workloads/reth-mainnet"] },
  { id: "workloads/reth-source-build", ecosystem: "reth", summary: "Compile and benchmark a changed Reth client revision",
    recipe: "reth-source", profile: "reth-source", status: "validated", inputs: ["repo", "exact ref", "workload"], requires: [],
    evidence: "2026-09-14: native source workload and current-head PR 26924 benchmark passed; no baseline speedup claimed",
    related: ["workloads/reth-development", "workloads/reth-mainnet"] },
  { id: "workloads/reth-mainnet", ecosystem: "reth", summary: "Snapshot-backed execution plus Lighthouse with paired readiness",
    recipe: "reth-synced", profile: "reth-synced", status: "validated", inputs: ["pinned manifest", "fresh verified checkpoint", "head-age bound"],
    requires: ["manifest-derived disk and transfer budget", "separate import and sync jobs"],
    evidence: "2026-09-14: paired readiness and managed warm restart passed; readiness later lost consensusSynced",
    related: ["workloads/reth-source-build", "workloads/base-node", "workloads/bsc-node"] },
  { id: "workloads/tempo-development", ecosystem: "tempo", summary: "Tempo-native transaction and RPC checks on an isolated dev chain",
    recipe: "tempo", profile: "runtime", status: "validated", inputs: ["workload", "transaction type and fee token"], requires: ["transaction signer supplied separately; Tempo-aware signing for type 0x76"],
    evidence: "2026-09-15: Tempo 1.14.0/Cast 1.8.1; type-2 and native 0x76 execution, batch rollback, sponsorship and independent nonce lanes passed; AlphaUSD fees and four native rejection controls verified; expiring nonces/access keys untested",
    related: ["workloads/tempo-contracts", "workloads/tempo-source-build"] },
  { id: "workloads/tempo-contracts", ecosystem: "tempo", summary: "Tempo EVM contract tests with Forge's explicit Tempo network",
    recipe: "foundry", profile: "runtime", status: "validated", inputs: ["project", "hardfork"], requires: ["project compiler and dependencies"],
    evidence: "2026-09-14: Forge 1.8.1 Tempo builtin assertions, T4/T5 activation boundaries, and Ethereum negative controls passed; model tests, not node transactions",
    related: ["workloads/tempo-development", "workloads/foundry-tests"] },
  { id: "workloads/tempo-source-build", ecosystem: "tempo", summary: "Compile a changed Tempo client and run protocol-specific tests",
    recipe: "tempo-source", profile: "tempo-source", status: "validated", inputs: ["repo", "exact ref", "workload"], requires: [],
    evidence: "2026-09-14: native Tempo source workload passed; public-network consensus is not established",
    related: ["workloads/tempo-development", "workloads/tempo-contracts"] },
  { id: "workloads/base-contract-fork", ecosystem: "base", summary: "Own-contract execution against fixed Base state, not a Base node",
    recipe: "foundry", profile: "runtime", status: "validated", inputs: ["project", "RPC URL", "fixed block and hash", "hardfork and isolation mode"],
    requires: ["RPC historical state access", "project compiler and dependencies"],
    evidence: "2026-09-15: block 51307369 pinned Isthmus isolated WETH roundtrip, L1 fee-vault accounting and one-wei funding boundary passed; no-isolate negative controls failed as expected; synthetic fees, not signed Base transaction pricing or consensus",
    related: ["workloads/foundry-tests", "workloads/base-node"] },
  { id: "workloads/base-node", ecosystem: "base", summary: "Base execution/consensus node: integration guidance, no bundled recipe yet",
    recipe: null, profile: null, status: "unavailable", inputs: ["client pins", "manifest", "L1 execution and beacon endpoints"],
    requires: ["Base-specific recipe, resource sizing, and readiness validation"], related: ["workloads/base-contract-fork", "workloads/reth-mainnet"] },
  { id: "workloads/bsc-contract-fork", ecosystem: "bsc", summary: "Own-contract execution against fixed BSC state, not Parlia validation",
    recipe: "foundry", profile: "runtime", status: "validated", inputs: ["project", "RPC URL", "fixed block and hash", "Ethereum-model compatibility"],
    requires: ["RPC historical state access", "project compiler and dependencies"],
    evidence: "2026-09-14: block 121873529 WBNB roundtrip passed under Ethereum rules; native 0x64 call differed from BSC RPC; not BSC precompile or Parlia validation",
    related: ["workloads/foundry-tests", "workloads/bsc-node"] },
  { id: "workloads/bsc-node", ecosystem: "bsc", summary: "BSC Geth/Parlia or Reth-BSC node: choose a client before sizing",
    recipe: null, profile: null, status: "unavailable", inputs: ["client pin", "genesis/config", "compatible snapshot"],
    requires: ["client-specific recipe, resource sizing, and readiness validation"], related: ["workloads/bsc-contract-fork", "workloads/reth-mainnet"] },
];
